apiVersion: hybernate.io/v1alpha1
kind: WorkloadPolicy
metadata:
  labels:
    app.kubernetes.io/name: hybernate
    app.kubernetes.io/managed-by: kustomize
  name: workloadpolicy-sample
  namespace: staging
spec:
  targetKinds:
    - Deployment
    - StatefulSet
  mode: suggest
  scanInterval: 10m
  cpuIdleThreshold: 10
  memoryIdleThreshold: 10
  cpuWastefulThreshold: 30
  memoryWastefulThreshold: 30
  rightSizeTarget: 70
  dryRun: true
