apiVersion: hybernate.io/v1alpha1
kind: ManagedWorkload
metadata:
  labels:
    app.kubernetes.io/name: hybernate
    app.kubernetes.io/managed-by: kustomize
  name: managedworkload-sample
  namespace: staging
spec:
  target:
    kind: Deployment
    name: api-server
  idlePolicy:
    cpuIdleThreshold: 10
    memoryIdleThreshold: 10
    gracePeriod: "5m"
    autoResume: true
  prediction:
    confidence: 85
  dryRun: true
