//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostStatus) DeepCopyInto(out *CostStatus) {
	*out = *in
	out.CurrentMonthCPUHours = in.CurrentMonthCPUHours.DeepCopy()
	out.CurrentMonthMemoryHours = in.CurrentMonthMemoryHours.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostStatus.
func (in *CostStatus) DeepCopy() *CostStatus {
	if in == nil {
		return nil
	}
	out := new(CostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostTrackingSpec) DeepCopyInto(out *CostTrackingSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostTrackingSpec.
func (in *CostTrackingSpec) DeepCopy() *CostTrackingSpec {
	if in == nil {
		return nil
	}
	out := new(CostTrackingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestroySpec) DeepCopyInto(out *DestroySpec) {
	*out = *in
	if in.PVCRetention != nil {
		in, out := &in.PVCRetention, &out.PVCRetention
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PVCRetentionWarning != nil {
		in, out := &in.PVCRetentionWarning, &out.PVCRetentionWarning
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestroySpec.
func (in *DestroySpec) DeepCopy() *DestroySpec {
	if in == nil {
		return nil
	}
	out := new(DestroySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestroyStatus) DeepCopyInto(out *DestroyStatus) {
	*out = *in
	if in.DestroyedAt != nil {
		in, out := &in.DestroyedAt, &out.DestroyedAt
		*out = (*in).DeepCopy()
	}
	if in.PVCRetentionExpiresAt != nil {
		in, out := &in.PVCRetentionExpiresAt, &out.PVCRetentionExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestroyStatus.
func (in *DestroyStatus) DeepCopy() *DestroyStatus {
	if in == nil {
		return nil
	}
	out := new(DestroyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdlePolicySpec) DeepCopyInto(out *IdlePolicySpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]ProbeSpec, len(*in))
		copy(*out, *in)
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdlePolicySpec.
func (in *IdlePolicySpec) DeepCopy() *IdlePolicySpec {
	if in == nil {
		return nil
	}
	out := new(IdlePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkload) DeepCopyInto(out *ManagedWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkload.
func (in *ManagedWorkload) DeepCopy() *ManagedWorkload {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkloadList) DeepCopyInto(out *ManagedWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkloadList.
func (in *ManagedWorkloadList) DeepCopy() *ManagedWorkloadList {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkloadSpec) DeepCopyInto(out *ManagedWorkloadSpec) {
	*out = *in
	out.Target = in.Target
	if in.DesiredState != nil {
		in, out := &in.DesiredState, &out.DesiredState
		*out = new(DesiredState)
		**out = **in
	}
	if in.IdlePolicy != nil {
		in, out := &in.IdlePolicy, &out.IdlePolicy
		*out = new(IdlePolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ScalePolicy != nil {
		in, out := &in.ScalePolicy, &out.ScalePolicy
		*out = new(ScalePolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(PauseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Destroy != nil {
		in, out := &in.Destroy, &out.Destroy
		*out = new(DestroySpec)
		(*in).DeepCopyInto(*out)
	}
	out.Prediction = in.Prediction
	if in.CostTracking != nil {
		in, out := &in.CostTracking, &out.CostTracking
		*out = new(CostTrackingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkloadSpec.
func (in *ManagedWorkloadSpec) DeepCopy() *ManagedWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkloadStatus) DeepCopyInto(out *ManagedWorkloadStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(PauseStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Scale != nil {
		in, out := &in.Scale, &out.Scale
		*out = new(ScaleStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Destroy != nil {
		in, out := &in.Destroy, &out.Destroy
		*out = new(DestroyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Prediction != nil {
		in, out := &in.Prediction, &out.Prediction
		*out = new(PredictionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(CostStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastActedAt != nil {
		in, out := &in.LastActedAt, &out.LastActedAt
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkloadStatus.
func (in *ManagedWorkloadStatus) DeepCopy() *ManagedWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PauseSpec) DeepCopyInto(out *PauseSpec) {
	*out = *in
	if in.ExpireAfter != nil {
		in, out := &in.ExpireAfter, &out.ExpireAfter
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PauseSpec.
func (in *PauseSpec) DeepCopy() *PauseSpec {
	if in == nil {
		return nil
	}
	out := new(PauseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PauseStatus) DeepCopyInto(out *PauseStatus) {
	*out = *in
	if in.PausedAt != nil {
		in, out := &in.PausedAt, &out.PausedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PauseStatus.
func (in *PauseStatus) DeepCopy() *PauseStatus {
	if in == nil {
		return nil
	}
	out := new(PauseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionSpec) DeepCopyInto(out *PredictionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionSpec.
func (in *PredictionSpec) DeepCopy() *PredictionSpec {
	if in == nil {
		return nil
	}
	out := new(PredictionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionStatus) DeepCopyInto(out *PredictionStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionStatus.
func (in *PredictionStatus) DeepCopy() *PredictionStatus {
	if in == nil {
		return nil
	}
	out := new(PredictionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeSpec) DeepCopyInto(out *ProbeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeSpec.
func (in *ProbeSpec) DeepCopy() *ProbeSpec {
	if in == nil {
		return nil
	}
	out := new(ProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDirectionSpec) DeepCopyInto(out *ScaleDirectionSpec) {
	*out = *in
	if in.Stabilization != nil {
		in, out := &in.Stabilization, &out.Stabilization
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxStep != nil {
		in, out := &in.MaxStep, &out.MaxStep
		*out = new(int)
		**out = **in
	}
	if in.Guard != nil {
		in, out := &in.Guard, &out.Guard
		*out = make([]ProbeSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDirectionSpec.
func (in *ScaleDirectionSpec) DeepCopy() *ScaleDirectionSpec {
	if in == nil {
		return nil
	}
	out := new(ScaleDirectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalePolicySpec) DeepCopyInto(out *ScalePolicySpec) {
	*out = *in
	if in.Down != nil {
		in, out := &in.Down, &out.Down
		*out = new(ScaleDirectionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Up != nil {
		in, out := &in.Up, &out.Up
		*out = new(ScaleDirectionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalePolicySpec.
func (in *ScalePolicySpec) DeepCopy() *ScalePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ScalePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleStatus) DeepCopyInto(out *ScaleStatus) {
	*out = *in
	if in.ScaledAt != nil {
		in, out := &in.ScaledAt, &out.ScaledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleStatus.
func (in *ScaleStatus) DeepCopy() *ScaleStatus {
	if in == nil {
		return nil
	}
	out := new(ScaleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
