//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivitySpec) DeepCopyInto(out *ActivitySpec) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = make([]PrometheusActivity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivitySpec.
func (in *ActivitySpec) DeepCopy() *ActivitySpec {
	if in == nil {
		return nil
	}
	out := new(ActivitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityStatus) DeepCopyInto(out *ActivityStatus) {
	*out = *in
	in.LastActivityTime.DeepCopyInto(&out.LastActivityTime)
	if in.PauseAt != nil {
		in, out := &in.PauseAt, &out.PauseAt
		*out = (*in).DeepCopy()
	}
	if in.LastEvaluatedTime != nil {
		in, out := &in.LastEvaluatedTime, &out.LastEvaluatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityStatus.
func (in *ActivityStatus) DeepCopy() *ActivityStatus {
	if in == nil {
		return nil
	}
	out := new(ActivityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostRates) DeepCopyInto(out *CostRates) {
	*out = *in
	if in.CPUPerHour != nil {
		in, out := &in.CPUPerHour, &out.CPUPerHour
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MemoryPerHour != nil {
		in, out := &in.MemoryPerHour, &out.MemoryPerHour
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StoragePerMonth != nil {
		in, out := &in.StoragePerMonth, &out.StoragePerMonth
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostRates.
func (in *CostRates) DeepCopy() *CostRates {
	if in == nil {
		return nil
	}
	out := new(CostRates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostStatus) DeepCopyInto(out *CostStatus) {
	*out = *in
	out.CurrentMonthCPUHours = in.CurrentMonthCPUHours.DeepCopy()
	out.CurrentMonthMemoryHours = in.CurrentMonthMemoryHours.DeepCopy()
	out.CurrentMonthStorageHours = in.CurrentMonthStorageHours.DeepCopy()
	if in.ListRates != nil {
		in, out := &in.ListRates, &out.ListRates
		*out = new(CostRates)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceReduction != nil {
		in, out := &in.ResourceReduction, &out.ResourceReduction
		*out = new(ResourceReduction)
		**out = **in
	}
	if in.LastAccumulatedAt != nil {
		in, out := &in.LastAccumulatedAt, &out.LastAccumulatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostStatus.
func (in *CostStatus) DeepCopy() *CostStatus {
	if in == nil {
		return nil
	}
	out := new(CostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostTrackingSpec) DeepCopyInto(out *CostTrackingSpec) {
	*out = *in
	if in.Rates != nil {
		in, out := &in.Rates, &out.Rates
		*out = new(CostRates)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostTrackingSpec.
func (in *CostTrackingSpec) DeepCopy() *CostTrackingSpec {
	if in == nil {
		return nil
	}
	out := new(CostTrackingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRef) DeepCopyInto(out *DependencyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRef.
func (in *DependencyRef) DeepCopy() *DependencyRef {
	if in == nil {
		return nil
	}
	out := new(DependencyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoormanRoute) DeepCopyInto(out *DoormanRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoormanRoute.
func (in *DoormanRoute) DeepCopy() *DoormanRoute {
	if in == nil {
		return nil
	}
	out := new(DoormanRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DryRunStatus) DeepCopyInto(out *DryRunStatus) {
	*out = *in
	in.Since.DeepCopyInto(&out.Since)
	out.Slept = in.Slept
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSnapshot)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DryRunStatus.
func (in *DryRunStatus) DeepCopy() *DryRunStatus {
	if in == nil {
		return nil
	}
	out := new(DryRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdlePolicySpec) DeepCopyInto(out *IdlePolicySpec) {
	*out = *in
	if in.IdleAfter != nil {
		in, out := &in.IdleAfter, &out.IdleAfter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Activity != nil {
		in, out := &in.Activity, &out.Activity
		*out = new(ActivitySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdlePolicySpec.
func (in *IdlePolicySpec) DeepCopy() *IdlePolicySpec {
	if in == nil {
		return nil
	}
	out := new(IdlePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkload) DeepCopyInto(out *ManagedWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkload.
func (in *ManagedWorkload) DeepCopy() *ManagedWorkload {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkloadList) DeepCopyInto(out *ManagedWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkloadList.
func (in *ManagedWorkloadList) DeepCopy() *ManagedWorkloadList {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkloadSpec) DeepCopyInto(out *ManagedWorkloadSpec) {
	*out = *in
	out.Target = in.Target
	if in.DesiredState != nil {
		in, out := &in.DesiredState, &out.DesiredState
		*out = new(DesiredState)
		**out = **in
	}
	if in.IdlePolicy != nil {
		in, out := &in.IdlePolicy, &out.IdlePolicy
		*out = new(IdlePolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]DependencyRef, len(*in))
		copy(*out, *in)
	}
	if in.Wake != nil {
		in, out := &in.Wake, &out.Wake
		*out = new(WakeSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Prediction = in.Prediction
	if in.CostTracking != nil {
		in, out := &in.CostTracking, &out.CostTracking
		*out = new(CostTrackingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkloadSpec.
func (in *ManagedWorkloadSpec) DeepCopy() *ManagedWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkloadStatus) DeepCopyInto(out *ManagedWorkloadStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(PauseStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastScaledUp != nil {
		in, out := &in.LastScaledUp, &out.LastScaledUp
		*out = new(ScaledUp)
		(*in).DeepCopyInto(*out)
	}
	if in.Prediction != nil {
		in, out := &in.Prediction, &out.Prediction
		*out = new(PredictionStatus)
		**out = **in
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(CostStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Doorman != nil {
		in, out := &in.Doorman, &out.Doorman
		*out = make([]DoormanRoute, len(*in))
		copy(*out, *in)
	}
	if in.Activity != nil {
		in, out := &in.Activity, &out.Activity
		*out = new(ActivityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(DryRunStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastActedAt != nil {
		in, out := &in.LastActedAt, &out.LastActedAt
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkloadStatus.
func (in *ManagedWorkloadStatus) DeepCopy() *ManagedWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PauseStatus) DeepCopyInto(out *PauseStatus) {
	*out = *in
	if in.PausedAt != nil {
		in, out := &in.PausedAt, &out.PausedAt
		*out = (*in).DeepCopy()
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSnapshot)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PauseStatus.
func (in *PauseStatus) DeepCopy() *PauseStatus {
	if in == nil {
		return nil
	}
	out := new(PauseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionSpec) DeepCopyInto(out *PredictionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionSpec.
func (in *PredictionSpec) DeepCopy() *PredictionSpec {
	if in == nil {
		return nil
	}
	out := new(PredictionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionStatus) DeepCopyInto(out *PredictionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionStatus.
func (in *PredictionStatus) DeepCopy() *PredictionStatus {
	if in == nil {
		return nil
	}
	out := new(PredictionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusActivity) DeepCopyInto(out *PrometheusActivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusActivity.
func (in *PrometheusActivity) DeepCopy() *PrometheusActivity {
	if in == nil {
		return nil
	}
	out := new(PrometheusActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReduction) DeepCopyInto(out *ResourceReduction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReduction.
func (in *ResourceReduction) DeepCopy() *ResourceReduction {
	if in == nil {
		return nil
	}
	out := new(ResourceReduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSnapshot) DeepCopyInto(out *ResourceSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSnapshot.
func (in *ResourceSnapshot) DeepCopy() *ResourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(ResourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaledUp) DeepCopyInto(out *ScaledUp) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaledUp.
func (in *ScaledUp) DeepCopy() *ScaledUp {
	if in == nil {
		return nil
	}
	out := new(ScaledUp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WakeSpec) DeepCopyInto(out *WakeSpec) {
	*out = *in
	if in.OnRequest != nil {
		in, out := &in.OnRequest, &out.OnRequest
		*out = new(bool)
		**out = **in
	}
	if in.MaxWait != nil {
		in, out := &in.MaxWait, &out.MaxWait
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Page != nil {
		in, out := &in.Page, &out.Page
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WakeSpec.
func (in *WakeSpec) DeepCopy() *WakeSpec {
	if in == nil {
		return nil
	}
	out := new(WakeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
