apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hybernate.fullname" . }}-manager
  labels:
    {{- include "hybernate.labels" . | nindent 4 }}
rules:
  {{- include "hybernate.managerClusterRules" . | nindent 2 }}
  {{- if not .Values.watchNamespaces }}
  {{- include "hybernate.managerRules" . | nindent 2 }}
  {{- end }}
{{- range .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hybernate.fullname" $ }}-manager
  namespace: {{ . }}
  labels:
    {{- include "hybernate.labels" $ | nindent 4 }}
rules:
  {{- include "hybernate.managerRules" $ | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hybernate.fullname" $ }}-manager
  namespace: {{ . }}
  labels:
    {{- include "hybernate.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hybernate.fullname" $ }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "hybernate.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
