{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybernate.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hybernate.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "hybernate.selectorLabels" . | nindent 4 }}
{{- end }}
