/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package cost

import (
	"bufio"
	"bytes"
	"compress/gzip"
	_ "embed"
	"fmt"
	"strconv"
	"strings"
	"sync"
)

// prices.csv.gz is generated by hack/prices: run `make prices`.
//
//go:embed prices.csv.gz
var pricesFile []byte

// NodeType is how a node is priced, from its well-known labels.
type NodeType struct {
	InstanceType string `json:"instanceType"`
	Region       string `json:"region"`
	Spot         bool   `json:"spot,omitempty"`
}

// spotLabels mark a node as spot or preemptible capacity, whose price
// changes by the hour; it's priced at on-demand.
var spotLabels = map[string]string{
	"karpenter.sh/capacity-type":            "spot",
	"eks.amazonaws.com/capacityType":        "SPOT",
	"cloud.google.com/gke-spot":             "true",
	"cloud.google.com/gke-preemptible":      "true",
	"kubernetes.azure.com/scalesetpriority": "spot",
}

// NodeTypeOf reads a node's instance type, region, and whether it's spot
// from its labels.
func NodeTypeOf(labels map[string]string) NodeType {
	t := NodeType{
		InstanceType: labels["node.kubernetes.io/instance-type"],
		Region:       labels["topology.kubernetes.io/region"],
	}
	for key, value := range spotLabels {
		if labels[key] == value {
			t.Spot = true
		}
	}
	return t
}

// ListPrice is a node type's on-demand list price, as rates.
type ListPrice struct {
	Provider string
	Rates    Rates
}

var listed = struct {
	sync.Mutex
	prices map[NodeType]*ListPrice
}{prices: map[NodeType]*ListPrice{}}

// ListPriceOf is a node type's on-demand list price, and false when the
// table doesn't have it. A cluster has few node types, so each is looked up
// in the table once, rather than the table kept in memory.
func ListPriceOf(t NodeType) (ListPrice, bool) {
	key := NodeType{InstanceType: t.InstanceType, Region: t.Region}
	listed.Lock()
	defer listed.Unlock()
	p, seen := listed.prices[key]
	if !seen {
		found, ok, err := lookUp(t.InstanceType, t.Region)
		if err != nil {
			return ListPrice{}, false
		}
		if ok {
			p = &found
		}
		listed.prices[key] = p
	}
	if p == nil {
		return ListPrice{}, false
	}
	return *p, true
}

// cpuToMemory is what a vCPU costs against a GiB of memory, from the
// default rates, which are AWS's general-purpose instances. Providers
// price an instance as a whole, so this is how its price is split between
// what its pods request.
var cpuToMemory = DefaultRates.CPUPerHour / DefaultRates.MemoryPerHour

// splitHourly divides an instance's hourly price between its vCPUs and its
// memory in the default rates' proportion, so a memory-optimized instance's
// memory and a compute-optimized one's CPU come out at what they cost there.
func splitHourly(hourly, vcpu, memoryGiB float64) Rates {
	perGiB := hourly / (vcpu*cpuToMemory + memoryGiB)
	return Rates{CPUPerHour: perGiB * cpuToMemory, MemoryPerHour: perGiB, StoragePerMonth: DefaultRates.StoragePerMonth}
}

// tableName is how the table names an instance type. Instance type names
// don't collide across providers, so the provider isn't needed to find one.
// AKS labels nodes with the ARM size name, Standard_D4s_v5, which the
// table has as d4sv5.
func tableName(instanceType string) string {
	t := strings.ToLower(instanceType)
	if rest, ok := strings.CutPrefix(t, "standard_"); ok {
		t = strings.ReplaceAll(rest, "_", "")
	}
	return t
}

// lookUp finds an instance type's price in a region in the table.
func lookUp(instanceType, region string) (ListPrice, bool, error) {
	if instanceType == "" || region == "" {
		return ListPrice{}, false, nil
	}
	name, region := tableName(instanceType), strings.ToLower(region)
	gz, err := gzip.NewReader(bytes.NewReader(pricesFile))
	if err != nil {
		return ListPrice{}, false, fmt.Errorf("reading the price table: %w", err)
	}
	sc := bufio.NewScanner(gz)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for line := 1; sc.Scan(); line++ {
		fields := strings.Split(sc.Text(), ",")
		if len(fields) < 5 || fields[1] != name {
			continue
		}
		for _, field := range fields[4:] {
			r, price, _ := strings.Cut(field, "=")
			if r != region {
				continue
			}
			p, err := parseListing(fields, price, line)
			return p, err == nil, err
		}
		return ListPrice{}, false, nil
	}
	if err := sc.Err(); err != nil {
		return ListPrice{}, false, fmt.Errorf("reading the price table: %w", err)
	}
	return ListPrice{}, false, nil
}

func parseListing(fields []string, price string, line int) (ListPrice, error) {
	vcpu, err := strconv.ParseFloat(fields[2], 64)
	if err != nil {
		return ListPrice{}, fmt.Errorf("price table line %d: vCPUs: %w", line, err)
	}
	memory, err := strconv.ParseFloat(fields[3], 64)
	if err != nil {
		return ListPrice{}, fmt.Errorf("price table line %d: memory: %w", line, err)
	}
	hourly, err := strconv.ParseFloat(price, 64)
	if err != nil {
		return ListPrice{}, fmt.Errorf("price table line %d: price: %w", line, err)
	}
	return ListPrice{Provider: fields[0], Rates: splitHourly(hourly, vcpu, memory)}, nil
}

// Mean averages the rates of a workload's pods, which request the same, so
// it's what the workload costs per vCPU and GiB across the nodes it runs on.
func Mean(rates []Rates) Rates {
	var m Rates
	for _, r := range rates {
		m.CPUPerHour += r.CPUPerHour
		m.MemoryPerHour += r.MemoryPerHour
		m.StoragePerMonth += r.StoragePerMonth
	}
	n := float64(len(rates))
	if n == 0 {
		return m
	}
	m.CPUPerHour /= n
	m.MemoryPerHour /= n
	m.StoragePerMonth /= n
	return m
}
